import Head from "next/head"
import Link from "next/link"

import { IoMenuSharp } from "react-icons/io5"
import styles from "./Header.module.css"

interface HeaderProps {
	pageTitle: string
	headerTitle: string
}
const Header = (props: HeaderProps) => {
	const { pageTitle, headerTitle } = props

	return (
		<>
			<Head>
				<title>{`${pageTitle} - Accessible Web Dev`}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<header>
				<div className={styles.topBanner}>
					<Link href="/">Accessible Web Dev</Link>
					<button>
						<IoMenuSharp color="white" size="2.5rem" />
					</button>
				</div>
				<h1 className={styles.headerTitle}>Accessible {headerTitle}</h1>
			</header>
		</>
	)
}

export default Header
