import type { GetStaticPaths, GetStaticProps, NextPage } from "next"

import Layout from "../components/Layout/Layout"
import Head from "next/head"
import { capitalizeRoute } from "../utils"
import { pages } from "../data/pages"

// Components
import Animations from "../components/ContentTemplates/AnimationsTemplate"
import Audio from "../components/ContentTemplates/AudioTemplate"
import Captchas from "../components/ContentTemplates/CaptchasTemplate"
import Charts from "../components/ContentTemplates/ChartsTemplate"
import Icons from "../components/ContentTemplates/IconsTemplate"
import Images from "../components/ContentTemplates/ImagesTemplate"
import Video from "../components/ContentTemplates/VideoTemplate"
import path from "path"
import { promises as fs } from "fs"
interface IProps {
	page: string
}

const ContentPage: NextPage = (props) => {
	const { page } = props as IProps
	const title = capitalizeRoute(page)

	return (
		<>
			<Head>
				<title>{`${title} - Accessible Web Dev`}</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<Layout headerTitle={title} activeNavLink={`/${page}`}>
				<>
					{page === "animations" && <Animations />}
					{page === "Audio" && <Audio />}
					{page === "captchas" && <Captchas />}
					{page === "charts" && <Charts />}
					{page === "icons" && <Icons />}
					{page === "images" && <Images />}
					{page === "video" && <Video />}
				</>
			</Layout>
		</>
	)
}

export const getStaticPaths: GetStaticPaths = async (context) => {
	// const pagesDirectory = path.join(process.cwd(), "data", "pages")
	// const pages = await fs.readFile(pagesDirectory)

	console.log("Pages", pages)

	// Filter out the ones with no content eg home

	//   const paths = pages.map((page) => ({
	// 	params: { content: page.content },
	//   }))

	return {
		paths: [
			{ params: { content: "animations" } },
			{ params: { content: "audio" } },
			{ params: { content: "captchas" } },
			{ params: { content: "charts" } },
			{ params: { content: "icons" } },
			{ params: { content: "images" } },
			{ params: { content: "video" } },
		],
		fallback: false, // can also be true or 'blocking'
	}
}

export const getStaticProps: GetStaticProps = async (context) => {
	const content = context.params?.content

	return {
		props: {
			page: content,
		},
	}
}

export default ContentPage
