import type { NextPage } from "next"
import { useRouter } from "next/router"
import Layout from "../components/Layout/Layout"
import Head from "next/head"

const Home: NextPage = () => {
	const router = useRouter()
	return (
		<>
			<Head>
				<title>{`Home - Accessible Web Dev`}</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<Layout headerTitle="Web Dev" activeNavLink={router.pathname}>
				<p>Main page - coming soon</p>
			</Layout>
		</>
	)
}

export default Home
