import { NextPage } from "next"
import { useRouter } from "next/router"
import Head from "next/head"

//Components
import Layout from "../../components/Layout/Layout"

// Utils
import { capitalizeRouter } from "../../utils"

const AnimationsPage: NextPage = () => {
	const router = useRouter()
	const title = capitalizeRouter(router.pathname)
	return (
		<>
			<Head>
				<title>{`Animations - Accessible Web Dev`}</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<Layout headerTitle={title} activeNavLink={router.pathname}>
				<p>Animations - coming soon</p>
			</Layout>
		</>
	)
}

export default AnimationsPage

/*
Should have an alt text
Animation shows instructions:Short alt to describe animation. Long alt containing instructions.


*/
