import { NextPage } from "next"
import { useRouter } from "next/router"
import Layout from "../../components/Layout/Layout"
import { capitalizeRouter } from "../../utils"
import Head from "next/head"

const AudioPage: NextPage = () => {
	const router = useRouter()
	const title = capitalizeRouter(router.pathname)
	return (
		<>
			<Head>
				<title>{`Audio - Accessible Web Dev`}</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<Layout headerTitle={title} activeNavLink={router.pathname}>
				<p>Audio - coming soon</p>
			</Layout>
		</>
	)
}

export default AudioPage

/*
Audio recording - link to transcript directly after recording
Transcripts ideally identify speakers, and describe important/relevant/significant sounds
Audio used to signal correct/incorrect answers - provide text alternative too
*/
